name: pull-request-workflow
on: 
  push:
    branches:
      - master
  pull_request:

jobs:
  check-compilation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt-get install libsdl2-dev
      - run: sudo apt-get install libsdl2-ttf-dev
      - run: make
